# Generated by Django 3.1.5 on 2021-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0004_auto_20210404_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_id',
            field=models.CharField(default='DEF001', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(fields=('rest_id',), name='rest_id_constraint'),
        ),
    ]
