# Generated by Django 3.1.5 on 2021-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0005_auto_20210404_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
