# Generated by Django 3.1.5 on 2021-04-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0006_dish_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='rest_no',
            field=models.IntegerField(default=0),
        ),
    ]
