# Generated by Django 3.1.5 on 2021-04-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0007_global_rest_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='cnf_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='global',
            name='order_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='global',
            name='rest_no',
            field=models.IntegerField(default=1),
        ),
    ]
