# Generated by Django 3.1.5 on 2021-04-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0008_auto_20210405_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CON', 'Confirm')], default='PD', max_length=4),
        ),
    ]
