# Generated by Django 3.1.5 on 2021-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0011_reservations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='tables',
            field=models.IntegerField(null=True),
        ),
    ]
