# Generated by Django 3.1.5 on 2021-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteladmin', '0012_reservations_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
